name: Gremlin Core Build, Test, and Nondex

on:
  push:
    branches:
      - nondex_action  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Change this to your desired Java version
          distribution: 'adopt'  # Use AdoptOpenJDK distribution

      - name: Build with Maven
        run: mvn clean install -DskipTests -pl gremlin-core -am

      - name: Run specific test
        run: mvn -pl gremlin-core test -Dtest=org.apache.tinkerpop.gremlin.process.traversal.step.util.ParametersTest#shouldAllowNullValues

      - name: Run Nondex test
        run: mvn -pl gremlin-core edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.tinkerpop.gremlin.process.traversal.step.util.ParametersTest#shouldAllowNullValues

